/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#2563eb',
        secondary: '#1e40af',
        accent: '#3b82f6',
      },
    },
  },
  plugins: [],
  safelist: [
    'bg-primary',
    'bg-secondary', 
    'bg-accent',
    'text-primary',
    'text-secondary',
    'text-accent',
    'from-primary',
    'to-secondary',
    'to-accent',
    'via-secondary',
    'border-primary',
    'shadow-primary',
    'hover:bg-primary',
    'hover:bg-secondary',
    'hover:border-primary',
    'hover:shadow-primary',
    'hover:shadow-accent',
    'bg-primary/5',
    'bg-primary/10',
    'bg-primary/20',
    'bg-accent/5',
    'bg-accent/10',
    'bg-accent/20',
    'bg-secondary/5',
    'shadow-primary/10',
    'shadow-primary/20',
    'shadow-primary/30',
    'shadow-accent/10',
    'shadow-accent/20',
    'hover:shadow-primary/20',
    'hover:shadow-primary/30',
    'hover:shadow-accent/20',
    'hover:bg-primary/5',
    'hover:bg-primary/20',
    'hover:bg-accent/20',
    'hover:bg-accent/30',
    'hover:border-primary/20',
    'hover:border-primary/50',
    'dark:bg-gray-800',
    'dark:bg-gray-900',
    'dark:bg-gray-700',
    'dark:text-white',
    'dark:text-gray-200',
    'dark:text-gray-300',
    'dark:border-gray-700',
    'dark:hover:bg-gray-700',
  ]
}